from typing import Any

class Module:
    def _call__(self, x: Any) -> Any: ...

class Linear(Module):
    weight: Any
    bias: Any
    out_features: int
    in_features: int
    def _init__(self, in_features: int, out_features: int) -> None: ...

class ReLU(Module): ...
class Tanh(Module): ...
class Sigmoid(Module): ...
class MSELoss(Module): ...

class Sequential(Module):
    def _init__(self, *args: Any) -> None: ...
