"""Cache port — injected key/value cache for temporary execution state."""

from typing import Protocol


class CacheProvider(Protocol):
    def get(self, key: str) -> object | None: ...
    def set(self, key: str, value: object) -> None: ...
    def invalidate(self, key: str) -> None: ...
    def clear(self) -> None: ...
