"""Cache port — injected key/value cache for temporary execution state."""

from typing import Any, Protocol


class CacheProvider(Protocol):
    def get(self, key: str) -> Any | None: ...
    def set(self, key: str, value: Any) -> None: ...
    def invalidate(self, key: str) -> None: ...
    def clear(self) -> None: ...
