from typing import Any

# Minimal stubs for top-level torch symbols used by the project.

class Tensor: ...

def from_numpy(ndarray: Any) -> Tensor: ...
def device(obj: Any) -> Any: ...

class no_grad:
    def _enter__(self) -> None: ...
    def _exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...

class utils:
    class data:
        class TensorDataset:
            def _init__(self, *tensors: Any) -> None: ...

        class DataLoader:
            def _init__(
                self, dataset: Any, batch_size: int = ..., shuffle: bool = ...
            ) -> None: ...
