from typing import Any

def figure(**kwargs: Any) -> Any: ...
def plot(*args: Any, **kwargs: Any) -> Any: ...
def xlabel(*args: Any, **kwargs: Any) -> Any: ...
def ylabel(*args: Any, **kwargs: Any) -> Any: ...
def title(*args: Any, **kwargs: Any) -> Any: ...
def grid(*args: Any, **kwargs: Any) -> None: ...
def show() -> None: ...
def subplots(*args: Any, **kwargs: Any) -> Any: ...
def tight_layout(**kwargs: Any) -> None: ...
def colorbar(*args: Any, **kwargs: Any) -> Any: ...
def xticks(*args: Any, **kwargs: Any) -> Any: ...
def bar(*args: Any, **kwargs: Any) -> Any: ...
def legend(*args: Any, **kwargs: Any) -> Any: ...
def text(*args: Any, **kwargs: Any) -> Any: ...
def savefig(*args: Any, **kwargs: Any) -> Any: ...
def get_cmap(*args: Any, **kwargs: Any) -> Any: ...
def suptitle(*args: Any, **kwargs: Any) -> Any: ...
class cm:
    @staticmethod
    def get_cmap(*args: Any, **kwargs: Any) -> Any: ...
    @staticmethod
    def ScalarMappable(*args: Any, **kwargs: Any) -> Any: ...
