"""
This type stub file was generated by pyright.
"""

from torch import nn
from sentence_transformers import SentenceTransformer

class ModelLoader:
    def __init__(self) -> None:
        ...
    
    def load_vision_model(self) -> tuple[nn.Module, int, int]:
        ...
    
    def load_embedding_model(self) -> tuple[SentenceTransformer, int]:
        ...
    


model_loader = ...
