"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Iterator, Union
from collections.abc import MutableMapping

PathLike = Union[str, Path]
ConfigDict = dict[str, Any]
PROJECT_ROOT: Path = ...
CONFIG_FILE: Path = ...
SUB_CONFIG_MAPPING: dict[str, str] = ...
def ensure_dir(path: PathLike) -> None:
    ...

_sentinel = ...
class AutoSaveDict(MutableMapping):
    def __init__(self, data: dict[str, Any], save_callback: Any) -> None:
        ...
    
    def get(self, key: str, default: Any = ...) -> Any:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __iter__(self) -> Iterator[str]:
        ...
    
    def __len__(self) -> int:
        ...
    
    def copy(self) -> dict[str, Any]:
        ...
    
    def __repr__(self) -> str:
        ...
    


class Config(MutableMapping):
    """
    Configuration Manager.

    STRICT POLICY:
    It is strictly forbidden to provide a default value when accessing configuration keys.
    The goal is to ensure that ALL configuration values are loaded explicitly from the
    configuration files (JSON) and absolutely nowhere else.

    This prevents hidden hardcoded values in the codebase and ensures that the
    configuration files are the single source of truth.

    Usage of .get(key, default) will raise a ValueError.
    Use .get(key) (without default) or direct access [key]. Both will raise KeyError if missing.
    """
    def __init__(self, config_file: PathLike = ...) -> None:
        ...
    
    def get(self, key: str, default: Any = ...) -> Any:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, value: Any) -> None:
        ...
    
    def __delitem__(self, key: str) -> None:
        ...
    
    def __iter__(self) -> Iterator[str]:
        ...
    
    def __len__(self) -> int:
        ...
    
    def clear(self) -> None:
        """Clear cache to force reload from disk."""
        ...
    


config = ...
