"""
This type stub file was generated by pyright.
"""

from PIL import Image
from collections.abc import Callable
from typing import Any
from .vectors.image_vector import ImageVector

ImageEntry = tuple[str, dict[str, Any], str, str]
def process_single_batch(prepare_func: Callable[[list[str]], list[Image.Image]], analyze_func: Callable[[list[Image.Image], list[ImageEntry]], list[ImageEntry]], paths: list[str], data: list[ImageEntry]) -> list[ImageEntry]:
    ...

class ImageAnalysis(ImageVector):
    def __init__(self, raw_data: list[ImageEntry]) -> None:
        ...
    
    def analyze_image_batch(self, image_batch: list[Image.Image], data_batch: list[ImageEntry]) -> list[ImageEntry]:
        ...
    
    def analyze_images_from_paths(self, batch_size: int = ..., max_workers: int = ...) -> list[ImageEntry]:
        ...
    


