"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Iterator, TypeVar

R = TypeVar("R")

def load_single_jsonl(filename: str, skip_invalid: bool = ...) -> Iterator[Any]:
    ...

def write_single_jsonl(filename: str, data: list[Any], mode: str) -> None:
    ...

def parallel_for(
    fn: Callable[..., R],
    items: list[tuple[Any, ...]],
    *,
    max_workers: int = ...,
    batch_size: int = ...,
    desc: str = ...,
    unit: str = ...,
) -> list[R]: ...

def parallel_batch(fn: Callable[..., R], items: list[tuple[Any, ...]]) -> list[R]:
    ...

def discover_files(root: str) -> Iterator[tuple[str, str]]:
    ...

def collect_single_file(file: tuple[str, str]) -> tuple[str, dict[str, Any], str, str] | None:
    ...

def collect_valid_files(files: Iterator[tuple[str, str]], max_workers: int, scored_only: bool) -> list[tuple[str, dict[str, Any], str, str]]:
    ...

T = TypeVar("T")
def load_json(path: str, expect: type | tuple[type, ...] | None, default: T | None) -> tuple[T | Any, str | None]:
    ...

def atomic_write_json(path: str, data: Any, *, indent: int | None = ...) -> None:
    ...

def load_single_entry_mapping(path: str) -> tuple[dict[str, Any] | None, str | None, str | None]:
    ...

