"""
This type stub file was generated by pyright.
"""

from typing import Any

"""Small shared utilities used across the project.

The helpers here are intentionally lightweight and thoroughly covered by unit
tests. They are written to be defensive and to avoid raising for bad input where
possible.
"""
def parse_custom_text(val: Any = ...) -> dict[str, Any]:
    """Parse a stored custom text value into a dictionary.

    Accepts None, an already-parsed dict, or a string containing a Python
    literal representation (e.g., "{'a':1}"). Returns an empty dict for any
    invalid input.
    """
    ...

def first_present(d: dict[str, Any], keys: tuple[str, ...], default: Any = ...) -> Any:
    """Return the first key from ``keys`` present in ``d`` with a non-None value.

    If none of the keys are present, return ``default``.
    """
    ...

