"""
This type stub file was generated by pyright.
"""

import logging
from dataclasses import dataclass

logger: logging.Logger = ...
@dataclass
class HistoryEntry:
    batch_size: int
    delta_memory: int
    timestamp: float
    ...


@dataclass
class ProfileData:
    model_name: str
    device_name: str
    device_id: str
    total_memory: int
    model_memory_bytes: int
    fixed_overhead: int | None = ...
    pixel_cost: float | None = ...
    r_squared: float | None = ...
    history: dict[str, list[HistoryEntry]] = ...


class BatchSizer:
    def __init__(self) -> None:
        ...
    
    def get(self, width: int, height: int, rebuild: bool = ..., bound: int | None = ...) -> int:
        ...


