"""
This type stub file was generated by pyright.
"""

import numpy as np
import numpy.typing as npt
from typing import Any

def l2_normalize_batch(vectors: npt.NDArray[np.float32]) -> npt.NDArray[np.float32]:
    ...

def get_value_from_entry(entry: dict[str, Any], name: str, alias: list[str] | None = ...) -> Any:
    ...

